---
R1:
  hostname: 192.168.31.101
  port: 830
  username: john
  password: cisco
  platform: ios
  connection_options:
    netconf:
        extras:
            allow_agent: False
            hostkey_verify: False

R2:
  hostname: 192.168.31.102
  port: 830
  username: john
  password: cisco
  platform: ios
  connection_options:
    netconf:
        extras:
            allow_agent: False
            hostkey_verify: False

R3:
  hostname: 192.168.31.103
  port: 830
  username: john
  password: cisco
  platform: ios
  connection_options:
    netconf:
        extras:
            allow_agent: False
            hostkey_verify: False
